### ISSUE TITLE
Linux build is broken

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#64]
The regression appears to have occurred in commit f63d4da122c441b87488a2df833ec1b2254986c9 and carries through to the current head (810d2aa631624e3d08dc370218fe75136038f8ff)

**Comment by bpbond** [comment]
Broken how?

Note this is why I'd like to get issue #61 (continuous integration) implemented later this winter.

**Comment by rplzzz** [comment]
It fails to build.  The first error is:
```
csv_outputstream_visitor.cpp:260:64: error: macro "STREAM_MESSAGE" passed 4 arguments, but takes just 3
csv_outputstream_visitor.cpp: In member function ‘virtual void Hector::CSVOutputStreamVisitor::visit(Hector::OzoneComponent*)’:
```
At a glance it seems that what was meant was `STREAM_MESSAGE_DATE`, which appears to take 4 arguments.  What is puzzling to me is that it compiled at all, anywhere, since having the wrong number of arguments would seem to be a serious error on any compiler.

**Comment by bpbond** [comment]
This seems to be fixed in the master head, actually. Make sure you've synced up.

**Comment by rplzzz** [comment]
So it is.  The master head has other build errors; I went back to the last version that built without errors and worked forward from there.  The errors in the head relate to the `boost::array<>` class.
